Update 18-working-with-marketing.rst
writethedocs/www pull request #1168
Opened 2020-02-12 02:08 UTC by redweezul

Created summary for Chapter 18.

2020-02-15 13:14 UTC, StarfallProjects requested changes
Thanks for contributing :-)

Only changes are:
- making capitalization consistent
- removing a few "&" and "etc."

2020-02-15 13:14 UTC, StarfallProjects commented on docs/book-club/splunk-product-docs/18-working-with-marketing.rst
> +Docs can serve as marketing material, though they should aim for educating the user first & act as a sales pitch second. Marketing may not like the direct nature of docs, but it is crucial to maintai
```suggestion
Docs can serve as marketing material, though they should aim for educating the user first and act as a sales pitch second. Marketing may not like the direct nature of docs, but it is crucial to maintain honesty and directness.
```

2020-02-15 13:14 UTC, StarfallProjects commented on docs/book-club/splunk-product-docs/18-working-with-marketing.rst
> +Personas are a key element to both Tech Writers and Marketing. These do not always align though, as Marketing personas target buyers (Management), whereas docs target users (end users/developers).
```suggestion
Personas are a key element to both tech writers and marketing. These do not always align though, as marketing personas target buyers (management), whereas docs target users (end users/developers).
```

2020-02-15 13:14 UTC, StarfallProjects commented on docs/book-club/splunk-product-docs/18-working-with-marketing.rst
> +How can Marketing help Docs:
```suggestion
How can marketing help docs:
```

2020-02-15 13:14 UTC, StarfallProjects commented on docs/book-club/splunk-product-docs/18-working-with-marketing.rst
> +How Docs can Help Marketing:
```suggestion
How docs can help marketing:
```

2020-02-15 13:14 UTC, StarfallProjects commented on docs/book-club/splunk-product-docs/18-working-with-marketing.rst
> +* Your product knowledge can improve the relevance of Marketing content
```suggestion
* Your product knowledge can improve the relevance of marketing content
```

2020-02-15 13:14 UTC, StarfallProjects commented on docs/book-club/splunk-product-docs/18-working-with-marketing.rst
> +Get & stay in contact with Marketing. Working together helps tighten the link between your docs & marketing content, avoids confusion for the user, and can make for a sharper content experience from
```suggestion
Get and stay in contact with marketing. Working together helps tighten the link between your docs and marketing content, avoids confusion for the user, and can make for a sharper content experience from interest to implementation.
```

2020-02-15 13:14 UTC, StarfallProjects commented on docs/book-club/splunk-product-docs/18-working-with-marketing.rst
> +Key Takeaways from Discussion
```suggestion
Key takeaways from discussion
```

2020-02-15 13:14 UTC, StarfallProjects commented on docs/book-club/splunk-product-docs/18-working-with-marketing.rst
> +A big challenge: push-back from Marketing to make content more sales-y.
```suggestion
A big challenge: push-back from marketing to make content more sales-y.
```

2020-02-15 13:14 UTC, StarfallProjects commented on docs/book-club/splunk-product-docs/18-working-with-marketing.rst
> +Both tech writers & marketing aim to help a user achieve a goal: Selling the product that enables the user to achieve said goal (Marketing), and educating the user on how to use the product in this m
```suggestion
Both tech writers and marketing aim to help a user achieve a goal: selling the product that enables the user to achieve said goal (marketing), and educating the user on how to use the product in this manner (tech writer).
```

2020-02-15 13:14 UTC, StarfallProjects commented on docs/book-club/splunk-product-docs/18-working-with-marketing.rst
> +Tech Writers can share the following with Marketing:
```suggestion
Tech writers can share the following with marketing:
```

2020-02-15 13:14 UTC, StarfallProjects commented on docs/book-club/splunk-product-docs/18-working-with-marketing.rst
> +Marketing can share the following with Tech Writers:
```suggestion
Marketing can share the following with tech writers:
```

2020-02-15 13:14 UTC, StarfallProjects commented on docs/book-club/splunk-product-docs/18-working-with-marketing.rst
> +* Communications advice when you have to share bad news (forced plan changes/migrations, dropping a feature, etc.).
```suggestion
* Communications advice when you have to share bad news (such as forced plan changes/migrations or dropping a feature).
```

2020-02-15 13:14 UTC, StarfallProjects commented on docs/book-club/splunk-product-docs/18-working-with-marketing.rst
> +Use the same language to describe products, and how to use them. May require differences in tone between docs & marketing, but aim to keep the user experience as similar as possible.
```suggestion
Use the same language to describe products, and how to use them. May require differences in tone between docs and marketing, but aim to keep the user experience as similar as possible.
```

2020-02-15 17:10 UTC, redweezul commented
No problem. I accepted all these suggestions. If I'm doing this right, I'll submit a new pull request.

2020-02-16 17:57 UTC, StarfallProjects commented
@redweezul I think now they're all resolved we can just merge? But not sure if we need further approval from someone at WTD - @plaindocs ?

2020-02-16 21:56 UTC, plaindocs commented
As you're merging into your feature branch there is no need for further approval.

2020-02-16 21:56 UTC, merged