add clean CoC + response
writethedocs/www pull request #134
Opened 2017-02-01 01:04 UTC by Bradamant3

Sorry folks, made a real mess out of last PR for CoC response. This contains changes from PR 115 and 122 for the CoC, plus new CoC response. Note that I've implemented Erik's suggestion of a conduct@writethedocs.org email alias; not set in stone, but gives us a starting point. No phone numbers; we'll have to discuss how to manage that one.

2017-02-01 01:30 UTC, mjang commented on docs/code-of-conduct-response.rst
> +* A request for a public or private apology.
Since this seems to be in order of severity, I'd put the "apology" line before "A public reprimand"

2017-02-01 01:33 UTC, mjang approved these changes
LGTM with a couple of minor comments. Once merged, I think we'll want a "short version" for Meetups.

Hint: if the revs are short, I'd make the revs directly in this GH web interface.

2017-02-01 21:28 UTC, ericholscher commented
The reporting guide is a good thing for attendees for our events, but I don't know if we should remove our internal response docs. We need to have a standard way of dealing with things internally, which is more what the response docs were about. This feels like 3 different things:

* The COC which specifies the rules
* The reporting guide, which explains in more detail to attendees how to report issues
* A response guide, which is used internally to make sure people who receive the reports handle it properly.

If we wanted to update our response guide, we can steal that again from Django: https://github.com/django/code-of-conduct/blob/master/reports.md -- but it feels like a necessary part of this, which shouldn't be deleted.

2017-02-02 11:53 UTC, plaindocs approved these changes

2017-02-02 11:53 UTC, plaindocs commented on docs/code-of-conduct-response.rst
> +In general, in any Write the Docs space (conferences, meetup, Slack, forum), if you believe someone is violating the code of conduct we ask that you report it to the staff by emailing report_. All re
How about 

> if you believe someone is violating the code of conduct,  in any Write the Docs space (conferences, meetup, Slack, forum), please (or we ask that...) report it to the staff by emailing report_

2017-02-02 11:53 UTC, plaindocs commented on docs/code-of-conduct.rst
> +Diversity is one of our huge strengths. To support a welcoming environment for all, regardless of individual differences, we have a few ground rules that we ask people to adhere to when they're parti
I'd say "in this community" not "within this community"

2017-02-03 22:02 UTC, yo-bj commented on docs/code-of-conduct-response.rst
> +In general, in any Write the Docs space (conferences, meetup, Slack, forum), if you believe someone is violating the code of conduct we ask that you report it to the staff by emailing report_. All re
If the report includes a minor, there is a chance that Mandatory Reporting laws would apply; therefore, we might want to clarify the "All reports will be kept confidential" to reflect our legal obligation.

2017-02-03 22:02 UTC, yo-bj commented on docs/code-of-conduct-response.rst
> +* A request for a public or private apology.
Seems reasonable. +1

2017-02-03 22:02 UTC, yo-bj commented on docs/code-of-conduct-response.rst
> +Finally, the staff may choose to make a public report of the incident.
What are the criteria for making the report public?

2017-02-03 22:02 UTC, yo-bj commented on docs/code-of-conduct-response.rst
> +Only permanent resolutions (such as bans) may be appealed. To appeal a decision, contact the WTD staff at report_ with your appeal and they will review the case.
Will the same people who handled the initial report be asked to do the appeal as well? I would ask that we consider bringing in a separate set of folks in for appeals.

2017-02-07 20:12 UTC, ericholscher requested changes
The reporting guide is a good thing for attendees for our events, but I don't know if we should remove our internal response docs. We need to have a standard way of dealing with things internally, which is more what the response docs were about. This feels like 3 different things:

The COC which specifies the rules
The reporting guide, which explains in more detail to attendees how to report issues
A response guide, which is used internally to make sure people who receive the reports handle it properly.
If we wanted to update our response guide, we can steal that again from Django: https://github.com/django/code-of-conduct/blob/master/reports.md -- but it feels like a necessary part of this, which shouldn't be deleted.

2017-02-08 13:18 UTC, mjang commented on docs/code-of-conduct-response.rst
> +Finally, the staff may choose to make a public report of the incident.
If it comes to that, I'd ask for legal advice. But for the CoC, I might include an `if appropriate` clause, e.g.: "Finally, if appropriate, the staff may choose to make a public report of the incident."

2017-02-08 13:20 UTC, mjang commented on docs/code-of-conduct-response.rst
> +Only permanent resolutions (such as bans) may be appealed. To appeal a decision, contact the WTD staff at report_ with your appeal and they will review the case.
Maybe -- I think judges sometimes reverse their own rulings on appeal (after sleeping on it)

2017-02-08 16:47 UTC, yo-bj commented on docs/code-of-conduct-response.rst
> +Finally, the staff may choose to make a public report of the incident.
Ah, my "rules lawyer" brain is asking for criteria for the public to see. "If appropriate" is a step forward, though very vague. How about this: "Finally, depending on several factors surrounding the incident (scope, seriousness, legal obligations, etc.), the staff reserve the right to make a public report of the incident."

2017-02-14 21:43 UTC, thatdocslady commented
So I was refactoring the CoC when I realized that this amazing discussion has been happening while I wasn't being attentive. Now I see that there's a bunch of feedback that wasn't all addressed. @Bradamant3 are you planning to handle this soon? I also have some additions I wanted to make (which is why I refactored originally), so maybe we can merge this and open a follow-up issue for the open issues, since it looks to me largely resolved/awesome :)

2017-02-14 21:50 UTC, thatdocslady commented
Ok I vote to merge this PR for the sake of preserving the great additions that were made here, and then I will take my input from the PR I submitted #146 as well as some of the feedback suggestions from here and submit a new PR on top of these merged changes. Unless anyone has objections to this, I will do it tomorrow (it's late CET :).

2017-02-14 22:01 UTC, Bradamant3 commented
Go Mikey. I have neglected it for too long, so sorry! Thank you!

On Tue, Feb 14, 2017 at 4:50 PM, Mikey Ariel <notifications@github.com>
wrote:

> Ok I vote to merge this PR for the sake of preserving the great additions
> that were made here, and then I will take my input from the PR I submitted
> #146 <https://github.com/writethedocs/www/pull/146> as well as some of
> the feedback suggestions from here and submit a new PR on top of these
> merged changes. Unless anyone has objections to this, I will do it tomorrow
> (it's late CET :).
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/writethedocs/www/pull/134#issuecomment-279847163>, or mute
> the thread
> <https://github.com/notifications/unsubscribe-auth/AGnO1oKCvTEoWyvBgcNr4EVNQZ1QGEvPks5rciGXgaJpZM4LzX9d>
> .
>

2017-02-19 12:11 UTC, merged