Added meetups FAQ
writethedocs/www pull request #145
Opened 2017-02-14 20:39 UTC by thatdocslady

Based on multiple Trello[1][2] discussions, this is the start of a section that hopefully will address these and similar questions. Feel free to suggest other FAQs to add here. Remember this is aimed at meetup organizers but could be read by anyone (members, sponsors).

2017-02-20 18:49 UTC, ericholscher requested changes
Looks like solid changes. We should have a section that specifies what exactly a meetup needs to do in order to be "supported" by us -- and probably account for the case when it stops happening. I think we've talked about having 50 members, and at least 4 meetups in the last year/1 in the last quarter?

2017-02-20 18:49 UTC, ericholscher commented on docs/organizer-guide/meetups/faq-meetups.rst
> +encounter when you want to `start a meetup <http://www.writethedocs.org/organizer-guide/meetups/starting/>`_.
Might be useful to use the Sphinx doc linking syntax here, instead of pointing at the URL.

2017-02-20 18:49 UTC, ericholscher commented on docs/organizer-guide/meetups/faq-meetups.rst
> +for 3 months, which should give you enough time to establish a local presence and hopefully run a few meetups.
We should probably be more explicit about how we evaluate groups are the trial period.

2017-02-20 18:49 UTC, ericholscher commented on docs/organizer-guide/meetups/starting.rst
> +Before you get started, check out our `Meetup FAQ <http://www.writethedocs.org/organizer-guide/meetups/faq/>`_.
Similar re: Sphinx `:doc:` usage.

2017-02-21 05:18 UTC, mjang reviewed
I know Eric has suggested min 4 meetups/yr 50 members. I suggest a lower number (3/30) to accommodate smaller metro areas (e.g. Boise) or some in foreign locations that take time to get started (e.g. Barcelona).

2017-02-21 05:50 UTC, plaindocs commented
How about we make it 4 meetups per year, but focus less on the number of people? Excluding places purely on population density (effectively) seems unnecessary. So 4 / 24? might work?

2017-02-21 17:28 UTC, mjang commented on docs/organizer-guide/meetups/faq-meetups.rst
> +for 3 months, which should give you enough time to establish a local presence and hopefully run a few meetups.
"a few meetups" in 3 months?

2017-02-22 17:40 UTC, thatdocslady commented on docs/organizer-guide/meetups/faq-meetups.rst
> +encounter when you want to `start a meetup <http://www.writethedocs.org/organizer-guide/meetups/starting/>`_.
The main meetup page also has this format for links, I'm not sure this is critical at this point. Maybe we should do a general pass at these someday?

2017-02-22 17:47 UTC, thatdocslady commented
So I tried to distill the feedback suggestions from here into relevant information in the FAQ. During this process I somehow managed to mess up the rebase and took in a bunch of commits. @ericholscher help on the tech side if you don't mind?

2017-02-22 17:59 UTC, ericholscher approved these changes

2017-02-22 17:59 UTC, merged