Add initial Prague sponsors
writethedocs/www pull request #1479
Opened 2021-04-05 23:34 UTC by ericholscher

2021-04-06 08:07 UTC, plaindocs requested changes
Unless I'm missing something, our landing page doesn't show  sponsors, we should probably fix that.

2021-04-06 16:27 UTC, ericholscher commented
@plaindocs looks fine to me in preview?

2021-04-07 07:48 UTC, plaindocs approved these changes

2021-04-07 07:50 UTC, plaindocs commented
Memo to self, always check the add blocker.

2021-04-07 07:50 UTC, merged