WTD style guide command line section
writethedocs/www pull request #1501
Opened 2021-04-25 16:58 UTC by barriebyron

@theomelo and @barriebyron will work here, all contributions and partners welcome

2021-04-25 18:14 UTC, barriebyron commented
companion to https://github.com/writethedocs/www/pull/1504

2021-04-25 18:23 UTC, theomelo commented
companion to https://github.com/writethedocs/www/pull/1506

2021-04-25 23:05 UTC, barriebyron commented
@Bradamant3 please help us make it happen!

2021-04-26 08:28 UTC, plaindocs requested changes
This is great, I've made a suggested change, and will tackle the merge issue with #1504 and or #1508 when we get there.

2021-04-26 08:28 UTC, plaindocs commented on docs/guide/writing/style-guides.md
> +Mistakes in software are unavoidable. Users might click a link that turns out to be broken or they might perform an action only to be met with an error. When a user encounters a problem, it's importa
I'm not sure I would personally call that a 'mistake' though. The click is intentional, even if the link is broken. How about this? 

```suggestion
Errors in software are unavoidable. Users might click a link that turns out to be broken or they might perform an action only to be met with an unexpected outcome. When a user encounters a problem, it's important to write error messages in a way that doesn't alienate the user.
```

2021-04-26 08:33 UTC, plaindocs commented
Oh, and there is an introduced broken link due to a heading rename that could do with fixing

```
- docs/_build/html/blog/newsletter-november-2020/index.html
  *  linking to internal hash #reducing-bias-in-your-writing that does not exist (line 106)
     <a class="reference external" href="https://www.writethedocs.org/guide/writing/style-guides/#reducing-bias-in-your-writing">lists of resources for inclusive writing and accessibility tooling</a>
```

2021-04-26 15:03 UTC, barriebyron commented
hi @plaindocs the newsletter link will need updating to the new bias content section championed by @Bradamant3 
We'll also need to update the foundational resources section on https://www.writethedocs.org/guide/ after all of our sections are pinned down. 

I alphabetized our lists and made a few more edits in the PR. lmk what other changes might be required. thank you!

2021-04-26 15:23 UTC, plaindocs approved these changes

2021-04-26 15:25 UTC, plaindocs commented
@barriebyron looks good to me, press the green button once that double hyphen commit goes though (assuming CI passes).

2021-04-26 15:28 UTC, plaindocs commented on docs/guide/writing/style-guides.md
> +- [DigitalOcean Documentation Style Guide](<https://docs.digitalocean.com/style/>
I think you want 

[DigitalOcean Documentation Style Guide](https://docs.digitalocean.com/style/)

2021-04-26 15:28 UTC, plaindocs commented on docs/guide/writing/style-guides.md
> +- [Digital Ocean](<https://docs.digitalocean.com/release-notes/>
same here

2021-04-26 15:38 UTC, plaindocs commented
Preview here https://writethedocs-www--1501.org.readthedocs.build/guide/writing/style-guides/#style-guide-resources

2021-04-26 15:47 UTC, plaindocs commented
:tada: !

2021-04-26 15:48 UTC, merged

2021-04-26 16:31 UTC, barriebyron commented
thank you everyone for contributing and collaborating, our updated Style Guide page is live https://www.writethedocs.org/guide/writing/style-guides/