[Australia] - Publish conference recap and links
writethedocs/www pull request #2071
Opened 2024-01-05 11:33 UTC by swapnilogale

2024-01-05 12:14 UTC, swapnilogale commented
Waiting on videos to be uploaded and processed ⏳

2024-01-07 14:58 UTC, plaindocs requested changes
Few minor nits

2024-01-07 14:58 UTC, plaindocs commented on docs/conf/australia/2023/news/thanks-recap.rst
> +We are already in 2024 folks! Our `Portland conference <https://www.writethedocs.org/conf/portland/2024/>`__ is scheduled to happen 14-16 May and CFPs are now open.
I'd say "the CFP" or "the call for proposals"

2024-01-07 14:58 UTC, plaindocs commented on docs/conf/australia/2023/news/thanks-recap.rst
> +Around mid 2024, we will announce dates and more details for the Australian conference.
```suggestion
We will announce dates and more details for the next Australian conference in the middle of 2024.
```

2024-01-07 14:58 UTC, plaindocs commented on docs/conf/australia/2023/news/thanks-recap.rst
> +Whether you were able to come out this time or not, we hope to see you again next year – or even sooner at one of our other events!
Were there sponsors? We should list them in this post?

2024-01-07 22:03 UTC, plaindocs commented
@swapnilogale I was thinking more like this https://github.com/writethedocs/www/pull/2068/files#diff-270d41847245bf5dc3d34d4f475dca1bbf64bb319f5a33f7ac90b4fdb1c59b06R71-R84 but up to you

2024-01-07 22:03 UTC, plaindocs approved these changes

2024-01-07 22:08 UTC, swapnilogale commented
> @swapnilogale I was thinking more like this https://github.com/writethedocs/www/pull/2068/files#diff-270d41847245bf5dc3d34d4f475dca1bbf64bb319f5a33f7ac90b4fdb1c59b06R71-R84 but up to you

Yep that works too. I'll make the change later today and publish. Videos are all scheduled to go live at 5pm today AEDT, so I'll fix it before then and push.

2024-01-08 07:23 UTC, merged