Writing Day: Doc Detective and Docs as Test
writethedocs/www pull request #2100
Opened 2024-02-26 18:41 UTC by rosewms

First project for Writing Day!

----
📚 Documentation preview 📚: https://writethedocs-www--2100.org.readthedocs.build/

2024-02-26 18:45 UTC, rosewms commented
I'm also sending this PR to the project organizer for review.

I often make edits to the survey content to ensure it makes sense for the Writing Day Project List - since style and formatting is different in surveys vs web pages.

2024-02-26 19:16 UTC, hawkeyexl requested changes
Clarified "project"/"product".

2024-02-26 19:16 UTC, hawkeyexl commented on docs/conf/portland/2024/writing-day.rst
> +* Ensure consistent UX between docs, projects, or products.
```suggestion
* Ensure consistent UX between docs and products.
```

2024-02-26 19:16 UTC, hawkeyexl commented on docs/conf/portland/2024/writing-day.rst
> +Docs as Tests is a tool-agnostic strategy for validating doc content by performing documented tasks on projects using automation. By validating that doc contents work as written, you can:
```suggestion
Docs as Tests is a tool-agnostic strategy for validating doc content by performing documented tasks directly in your products using automation. By validating that doc contents work as written, you can: 
```

2024-02-26 19:16 UTC, hawkeyexl commented on docs/conf/portland/2024/writing-day.rst
> +Come by our table, and we'll help you set up Docs as Tests with whatever tools (such as Doc Detective) or strategies (like unit testing code snippets) are appropriate. Establish a zero-trust relation
```suggestion
Come by our table, and we'll help you set up Docs as Tests with whatever tools (such as Doc Detective) or strategies (like unit testing code snippets) are appropriate. Establish a zero-trust relationship between your docs and product, catching bugs in both as you go.
```

2024-02-26 19:16 UTC, hawkeyexl commented on docs/conf/portland/2024/writing-day.rst
> +Our Writing Day goal is to test at least 10 docs projects! We want every writer to be confident in their docs.
```suggestion
Our Writing Day goal is to test at least 10 docs sets! We want every writer to be confident in their docs. 
```

2024-02-27 10:00 UTC, plaindocs commented on docs/conf/portland/2024/writing-day.rst
> +`Doc Detective <https://doc-detective.com/>`__ is back at Writing Day again, this time with our friends, `Docs as Tests <www.docsastests.com>`__. Does your project or product have a UI? APIs? SDKs? W
```suggestion
`Doc Detective <https://doc-detective.com/>`__ is back at Writing Day again, this time with our friends, `Docs as Tests <http://www.docsastests.com>`__. Does your project or product have a UI? APIs? SDKs? We can help you test them and keep your docs accurate.
```

2024-02-27 16:33 UTC, rosewms commented
Thanks @hawkeyexl and @plaindocs - Sam if you approve this, I can merge it.

2024-02-27 17:20 UTC, plaindocs approved these changes
:shipit:

2024-02-28 17:22 UTC, merged