WD: Audinux project
writethedocs/www pull request #2200
Opened 2024-08-29 02:28 UTC by rosewms

Atlantic 2024 Writing Day project, Audinux.

Steps before publishing:

- [ ] Staff review of project to confirm Writing Day suitability
- [ ] Project lead/organizer review to confirm project content is good to go
- [ ] Final staff review before publishing

2024-08-29 08:00 UTC, plaindocs approved these changes

2024-08-29 08:00 UTC, plaindocs commented on docs/conf/atlantic/2024/writing-day.rst
> +
```suggestion
```

2024-08-29 08:00 UTC, plaindocs commented on docs/conf/atlantic/2024/writing-day.rst
> +Audinix - Stash and Publish a User Guide (Session 1)
Stash???

2024-08-29 08:00 UTC, plaindocs commented on docs/conf/atlantic/2024/writing-day.rst
> +- Rack and patchbay
This  is unrealistic, but sure :-D

2024-08-30 09:16 UTC, mxsasha approved these changes
Agreed with Sam, seems like a lot for one session

2024-08-30 18:00 UTC, hankuoffroad commented on docs/conf/atlantic/2024/writing-day.rst
> +Audinix - Stash and Publish a User Guide (Session 1)
Sorry, I've sprinkled a Git terminology 'Git stash', meaning temporarily saving the content in staging area. I'll be explaining that during introduction if that's ok. In particular, a new article requires step by step approaches of building paragraphs and setting them aside, picking some for final publication.

2024-08-31 09:55 UTC, ycollet approved these changes
Looks Good To Me !

2024-08-31 10:09 UTC, hankuoffroad commented
> Looks Good To Me !

I have created issue tickets in Audinux repo, so attendees can self-assign it and work whenever they're available during the day asynchronously. Due to time difference between US East and Europe, I would monitor WTD's Slack channel myself and PRs as well.

https://github.com/audinux/audinux.github.io/issues/created_by/hankuoffroad

2024-08-31 10:30 UTC, hankuoffroad requested changes
Submitting the changes for review. Thanks for your help.

2024-08-31 10:30 UTC, hankuoffroad commented on docs/conf/atlantic/2024/writing-day.rst
> +- Introduction to Audinux
Session 1
Introduction to Audinux
Intended audience
Content type
Tools for publication
End to end processes
Template: Initial configuration for music creation (Instrument: Electric guitar)
Audio tools

Session 2
How to find right Audio/Music packages for your creative work
Audio Plug-ins

Topics to choose from;
How to find subpackages that complement plugins and install subpackages
How to load plugins to DAW (Digital Audio Workstation) and OBS Studio
Rack and patchbay
Use cases: Home recording

2024-08-31 10:30 UTC, hankuoffroad commented on docs/conf/atlantic/2024/writing-day.rst
I've updated it on the Google Forms as well: https://docs.google.com/forms/d/e/1FAIpQLSe4uacCEfqIGMcjnO6UDA6ss0vUAKsSBsXg3-WhdjI0tHBqmA/viewform?edit2=2_ABaOnudDYJ7h1YGMNvs7ED31_W0irQWwptOL3Ct_Idwsma3RByoDrbALuZlvg5tVT4tFxlE

I've invited the maintainer of (Audinux GitHub ID: ycollet) for a joint review with me.

2024-08-31 10:30 UTC, hankuoffroad commented on docs/conf/atlantic/2024/writing-day.rst
Here is the project repository for participants to make PR: https://github.com/audinux/audinux.github.io/tree/main/pages/user_guide

2024-09-01 10:41 UTC, hankuoffroad commented on docs/conf/atlantic/2024/writing-day.rst
> +Audinix - Stash and Publish a User Guide (Session 1)
Audinux - Plan and Publish a User Guide

2024-09-01 10:42 UTC, hankuoffroad commented on docs/conf/atlantic/2024/writing-day.rst
> +Tentative outline and table of contents:
Session topics

2024-09-01 13:49 UTC, hankuoffroad commented on docs/conf/atlantic/2024/writing-day.rst
> +Audinix - Stash and Publish a User Guide (Session 1)
Audinux - Plan and Publish a User Guide

2024-09-01 13:51 UTC, hankuoffroad commented on docs/conf/atlantic/2024/writing-day.rst
> +Our plan is to create new documentation pages within the 'User Guide' templates. This means you can contribute using the GitHub web editor or using whatever Git-workflow from your favorite local writ
Delete: If you are unfamiliar with GitHub, we recommend using the `hackMD <https://hackmd.io/>`__ integration with GitHub.

2024-09-05 20:05 UTC, hankuoffroad requested changes

2024-09-05 20:05 UTC, hankuoffroad commented on docs/conf/atlantic/2024/writing-day.rst
> +Audinix - Plan and Publish a User Guide (All day)
Audinux

2024-09-05 20:21 UTC, hankuoffroad requested changes

2024-09-05 20:21 UTC, hankuoffroad commented on docs/conf/atlantic/2024/writing-day.rst
> +Our plan is to create new documentation pages within the 'User Guide' templates, check out our `project repository <https://github.com/audinux/audinux.github.io/tree/main/pages/user_guide)>`__. This
check out our `project repository <https://github.com/audinux/audinux.github.io/tree/main/pages/user_guide

// could you remove ) at the end of sentence? Thanks.

2024-09-06 18:10 UTC, rosewms commented
@hankuoffroad I am going to get this live. If any additional edits are needed, please submit a PR. Thanks!

2024-09-06 18:11 UTC, merged