2-months blog post and updated info for boat tour and social event
writethedocs/www pull request #262
Opened 2017-07-18 19:15 UTC by thatdocslady

All the updates. Please review :)

2017-07-18 19:25 UTC, plaindocs commented
I briefly checked this, didn't run it locally. Seems fine to me.

2017-07-18 19:31 UTC, mxsasha requested changes

2017-07-18 19:31 UTC, erikr commented on docs/conf/eu/2017/news/announcing-events-volunteers.rst
> +- **Lightning Talks.** One of our favorite traditions, `lightning talks <http://www.writethedocs.org/conf/eu/2017/lightning-talks/>`_ are as entertaining as they are informative. Each block of lightn
Should this be "sign up on the mornings" ?

2017-07-18 19:31 UTC, erikr commented on docs/conf/eu/2017/news/announcing-events-volunteers.rst
> +- **Unconference.** Parallel to the afternoon talks, you're welcome to join the `unconference sessions <http://www.writethedocs.org/conf/eu/2017/unconference/>`_. These freestyle sessions are a great
unconferene -> unconference

2017-07-18 20:42 UTC, ericholscher reviewed
LGTM over than these small nits.

2017-07-18 20:42 UTC, ericholscher commented on docs/conf/eu/2017/news/announcing-events-volunteers.rst
> +As always, Write the Docs events are more than just talks. Every year we try to maximize our attendees experience and invest in the social experience of being a part of our community.
2x experience? Maybe: "Every year we try to maximize our attendees enjoyment and invest in the social experience of being a part of our community"

2017-07-18 20:42 UTC, ericholscher commented on docs/conf/eu/2017/news/announcing-events-volunteers.rst
> +- **Boat Tour of Prague, Saturday September 9th**. If you're in town early (or if you're not sure whether to come early), you're invited to join us for a 2-hour cruise on the Vltava river, with a rel
The `(or if you're not sure whether to come early)` confuses the sentence a bit, and could probably be dropped, or made the primary part "If you're deciding if you want to come a day early"..

2017-07-18 20:42 UTC, ericholscher commented on docs/conf/eu/2017/news/announcing-events-volunteers.rst
> +- **Writing Day and Welcome Reception, Sunday September 10th**. We'll be soft-launching the conference with a `Writing Day <http://www.writethedocs.org/conf/eu/2017/writing-day/>`_  and Welcome Recep
soft-launching? Not sure what this means.

2017-07-18 20:43 UTC, ericholscher commented on docs/conf/eu/2017/news/announcing-events-volunteers.rst
> +As always, Write the Docs events are more than just talks. Every year we try to maximize our attendees experience and invest in the social experience of being a part of our community.
That still reads a bit passive voice. Needs less abstraction I think. "Every year we make sure to hold lots of social events to allow people to connect and form a community", or something.

2017-07-19 09:21 UTC, plaindocs commented on docs/conf/eu/2017/news/announcing-events-volunteers.rst
> +As always, Write the Docs events are more than just talks. Every year we try to maximize our attendees experience and invest in the social experience of being a part of our community.
> As always, Write the Docs events are more than just talks. We've a variety of events where you can meet the rest of the documentarian community. 

still not a huge fan. But simple is better here I think

2017-07-19 09:21 UTC, plaindocs commented on docs/conf/eu/2017/news/announcing-events-volunteers.rst
> +- **Boat Tour of Prague, Saturday September 9th**. If you're in town early (or if you're not sure whether to come early), you're invited to join us for a 2-hour cruise on the Vltava river, with a rel
Come to Prague early, and join us....

2017-07-19 09:27 UTC, plaindocs commented on docs/conf/eu/2017/news/index.rst
> +   announcing-events-volunteers
@thatdocslady sadly we gotta do this, if you just glob the files like it was before, the order doesn't work.

2017-07-19 10:06 UTC, thatdocslady commented on docs/conf/eu/2017/news/index.rst
> +   announcing-events-volunteers
ahhhh I forgot, thanks

2017-07-19 10:49 UTC, plaindocs commented on docs/conf/eu/2017/news/announcing-events-volunteers.rst
> +As always, Write the Docs events are more than just talks. Every year we offer a wider range of activities that give our community members different ways to socialize, collaborate, and connect.
<3

2017-07-19 10:50 UTC, plaindocs commented
LGTM

2017-07-19 10:50 UTC, merged