revise doc guide toc
writethedocs/www pull request #540
Opened 2018-05-06 19:28 UTC by Bradamant3

Work in progress. Not sure about how good to merge yet, but getting something up there to help folks visualize https://github.com/writethedocs/www/issues/527

2018-05-14 21:43 UTC, plaindocs commented
What is the status on this? I can take a deeper look, but probably fine to 'just merge' TM?

2018-05-14 22:43 UTC, Bradamant3 commented
I guess we can go ahead and merge. I'd like to get some editorial content in there about the documentation principles and style guides contributions, but I need to think -- and maybe discuss with some of y'all -- the best way to proceed. We don't have a DCO or any sort of contributor agreement, do we? Safe to assume that any and all content edits are OK?

2018-09-03 11:48 UTC, plaindocs commented
Oops, dropped the ball here. @Bradamant3 I'll leave this open till you're online and merge if that sounds good. Apologies.

2019-01-15 23:27 UTC, ericholscher commented
This is now conflicting. Seems valuable, so we should get it fixed up and merge it.

2019-01-16 01:25 UTC, Bradamant3 commented
@plaindocs @ericholscher conflicts fixed

2019-01-16 12:14 UTC, ericholscher reviewed
Looks good with a few nits.

2019-01-16 12:14 UTC, ericholscher commented on docs/guide/contributing.rst
> +* [Slack](https://writethedocs.slack.com/)
This is still in markdown

2019-01-16 12:14 UTC, ericholscher commented on docs/guide/index.rst
> +Take a look also at the `guidelines for contributing to the guide <contributing>`_. If you have any questions about contributing,
This should use `:doc:`, not a relative link, so that it works across builders.

2019-01-16 21:07 UTC, plaindocs requested changes
:+1: think I caught most of these

2019-01-16 21:07 UTC, plaindocs commented on docs/guide/contributing.rst
> +* [Slack](https://writethedocs.slack.com/)
```suggestion
- `Slack <http://slack.writethedocs.com/>`_
```

2019-01-16 21:07 UTC, plaindocs commented on docs/guide/contributing.rst
> +* [Write the Docs forum](http://forum.writethedocs.org/)
```suggestion
- `Forum <http://forum.writethedocs.org/>`_
```

2019-01-16 21:07 UTC, plaindocs commented on docs/guide/index.rst
> +Take a look also at the `guidelines for contributing to the guide <contributing>`_. If you have any questions about contributing,
```suggestion
Take a look also at the :doc:`guidelines for contributing to the guide <contributing>`. If you have any questions about contributing, 
```

2019-01-16 21:07 UTC, plaindocs commented on docs/guide/contributing.rst
> +# Community
```suggestion
Community
----------------
```

2019-01-16 21:07 UTC, plaindocs commented on docs/guide/contributing.rst
> +[How to Contribute to an Open Source Project on GitHub](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) is a great resource to help you get started.
```suggestion
`How to Contribute to an Open Source Project on GitHub <https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github>`_ is a great resource to help you get started.
```

2019-01-16 21:07 UTC, plaindocs commented on docs/guide/contributing.rst
> +You can also check out [the main website](http://www.writethedocs.org/meetups/) for a list of local meetups.
```suggestion
You can also check out our `local meetups <http://www.writethedocs.org/meetups>`_.
```

2019-01-17 01:29 UTC, Bradamant3 commented
perhaps GH's beta `commit suggestion` feature is not quite so cool? At any rate, seems travis is not happy on some of those commits ... or are they "just" waiting on a new build? Confused, but grateful to @plaindocs and amused also at my inability to stay in .rst after too long in .md.

2019-01-28 19:52 UTC, plaindocs approved these changes

2019-01-28 19:54 UTC, merged