First draft of February newsletter
writethedocs/www pull request #786
Opened 2019-01-30 19:49 UTC by bethaitman

WIP.

2019-01-30 20:24 UTC, plaindocs requested changes
Persnickety changes only.

2019-01-30 20:24 UTC, plaindocs commented on docs/blog/newsletter-february-2019.rst
> +In other news, on the conference front: we now have `dates for the 2019 Prague conference </conf/prague/2019/news/prague-19-dates/>`_! It'll be 15th-17th September, back in the gorgeous Auto Klub. Ti
```suggestion
In other news, on the conference front we now have `dates for the 2019 Prague conference </conf/prague/2019/news/prague-19-dates/>`_! It'll be 15th-17th September, back in the gorgeous Auto Klub. Ticket sales and call for proposals should open in March - keep your eyes peeled.
```

2019-01-30 20:24 UTC, plaindocs commented on docs/blog/newsletter-february-2019.rst
> +One topic that came up this month: how do you successfully deliver documentation when features roll out continuously... as in every two weeks?
Aren't all these topics that came up this month? :-p

2019-01-30 20:24 UTC, plaindocs commented on docs/blog/newsletter-february-2019.rst
> +A recent question about personal, work-related development goals produced quite a thread, and brought many common interests to the fore. Here are some of the areas the community wants to develop in 2
This implies to me that the community wants to develop them collaboratively, which isn't the case here. Right?

2019-01-30 20:24 UTC, plaindocs commented on docs/blog/newsletter-february-2019.rst
> +* Other ideas included working on graphics and illustration skills, contributing to tech communities (new meetups, new conferences, new outreach groups), working more deeply with the products you doc
```suggestion
* Other ideas included working on graphics and illustration skills, contributing to tech communities (new meetups, new conferences, new outreach groups), and working more deeply with the products you document - especially if they're for developers or sysadmins!
```

2019-01-30 20:24 UTC, plaindocs commented on docs/blog/newsletter-february-2019.rst
> +The takeaway is that you cannot save a bad design with documentation. Not even by documenting the bad design in bold and all caps.
<3

2019-01-30 20:24 UTC, plaindocs commented on docs/newsletter.rst
>  -------------
AND on the fly categorization. :tada:

2019-01-31 10:46 UTC, bethaitman commented on docs/blog/newsletter-february-2019.rst
> +In other news, on the conference front: we now have `dates for the 2019 Prague conference </conf/prague/2019/news/prague-19-dates/>`_! It'll be 15th-17th September, back in the gorgeous Auto Klub. Ti
The colon makes sense, doesn't it?

2019-01-31 10:47 UTC, bethaitman commented on docs/blog/newsletter-february-2019.rst
> +One topic that came up this month: how do you successfully deliver documentation when features roll out continuously... as in every two weeks?
Fair point!

2019-02-01 11:05 UTC, hillaryfraley submitted a review, later dismissed
Beth, I made my suggestions directly in the Jan 31 commit.

2019-02-01 17:43 UTC, plaindocs commented on docs/blog/newsletter-february-2019.rst
> +In other news, on the conference front: we now have `dates for the 2019 Prague conference </conf/prague/2019/news/prague-19-dates/>`_! It'll be 15th-17th September, back in the gorgeous Auto Klub. Ti
Yeah, i think so. I don't see that it adds anything over it not being there though? But probably pure personal preference, so disregard. :man_shrugging:

2019-02-01 17:44 UTC, plaindocs approved these changes

2019-02-04 13:11 UTC, merged